// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: textprocessor.proto

package textprocessor

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TextRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TextRequest) Reset() {
	*x = TextRequest{}
	mi := &file_textprocessor_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TextRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TextRequest) ProtoMessage() {}

func (x *TextRequest) ProtoReflect() protoreflect.Message {
	mi := &file_textprocessor_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TextRequest.ProtoReflect.Descriptor instead.
func (*TextRequest) Descriptor() ([]byte, []int) {
	return file_textprocessor_proto_rawDescGZIP(), []int{0}
}

func (x *TextRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type TextResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        int32                  `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TextResponse) Reset() {
	*x = TextResponse{}
	mi := &file_textprocessor_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TextResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TextResponse) ProtoMessage() {}

func (x *TextResponse) ProtoReflect() protoreflect.Message {
	mi := &file_textprocessor_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TextResponse.ProtoReflect.Descriptor instead.
func (*TextResponse) Descriptor() ([]byte, []int) {
	return file_textprocessor_proto_rawDescGZIP(), []int{1}
}

func (x *TextResponse) GetResult() int32 {
	if x != nil {
		return x.Result
	}
	return 0
}

var File_textprocessor_proto protoreflect.FileDescriptor

const file_textprocessor_proto_rawDesc = "" +
	"\n" +
	"\x13textprocessor.proto\x12\rtextprocessor\"!\n" +
	"\vTextRequest\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\"&\n" +
	"\fTextResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\x05R\x06result2W\n" +
	"\x0eTextProcessorA\x12E\n" +
	"\n" +
	"CountWords\x12\x1a.textprocessor.TextRequest\x1a\x1b.textprocessor.TextResponse2\\\n" +
	"\x0eTextProcessorB\x12J\n" +
	"\x0fCountCharacters\x12\x1a.textprocessor.TextRequest\x1a\x1b.textprocessor.TextResponseB\x12Z\x10./;textprocessorb\x06proto3"

var (
	file_textprocessor_proto_rawDescOnce sync.Once
	file_textprocessor_proto_rawDescData []byte
)

func file_textprocessor_proto_rawDescGZIP() []byte {
	file_textprocessor_proto_rawDescOnce.Do(func() {
		file_textprocessor_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_textprocessor_proto_rawDesc), len(file_textprocessor_proto_rawDesc)))
	})
	return file_textprocessor_proto_rawDescData
}

var file_textprocessor_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_textprocessor_proto_goTypes = []any{
	(*TextRequest)(nil),  // 0: textprocessor.TextRequest
	(*TextResponse)(nil), // 1: textprocessor.TextResponse
}
var file_textprocessor_proto_depIdxs = []int32{
	0, // 0: textprocessor.TextProcessorA.CountWords:input_type -> textprocessor.TextRequest
	0, // 1: textprocessor.TextProcessorB.CountCharacters:input_type -> textprocessor.TextRequest
	1, // 2: textprocessor.TextProcessorA.CountWords:output_type -> textprocessor.TextResponse
	1, // 3: textprocessor.TextProcessorB.CountCharacters:output_type -> textprocessor.TextResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_textprocessor_proto_init() }
func file_textprocessor_proto_init() {
	if File_textprocessor_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_textprocessor_proto_rawDesc), len(file_textprocessor_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_textprocessor_proto_goTypes,
		DependencyIndexes: file_textprocessor_proto_depIdxs,
		MessageInfos:      file_textprocessor_proto_msgTypes,
	}.Build()
	File_textprocessor_proto = out.File
	file_textprocessor_proto_goTypes = nil
	file_textprocessor_proto_depIdxs = nil
}
