# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: textprocessor.proto

require 'google/protobuf'


descriptor_data = "\n\x13textprocessor.proto\x12\rtextprocessor\"\x1b\n\x0bTextRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\"\x1e\n\x0cTextResponse\x12\x0e\n\x06result\x18\x01 \x01(\x05\x32W\n\x0eTextProcessorA\x12\x45\n\nCountWords\x12\x1a.textprocessor.TextRequest\x1a\x1b.textprocessor.TextResponse2\\\n\x0eTextProcessorB\x12J\n\x0f\x43ountCharacters\x12\x1a.textprocessor.TextRequest\x1a\x1b.textprocessor.TextResponseb\x06proto3"

pool = Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Textprocessor
  TextRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("textprocessor.TextRequest").msgclass
  TextResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("textprocessor.TextResponse").msgclass
end
