# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: textprocessor.proto for package 'textprocessor'

require 'grpc'
require_relative 'textprocessor_pb'

module Textprocessor
  module TextProcessorA
    class Service

      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'textprocessor.TextProcessorA'

      rpc :CountWords, ::Textprocessor::TextRequest, ::Textprocessor::TextResponse
    end

    Stub = Service.rpc_stub_class
  end
  module TextProcessorB
    class Service

      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'textprocessor.TextProcessorB'

      rpc :CountCharacters, ::Textprocessor::TextRequest, ::Textprocessor::TextResponse
    end

    Stub = Service.rpc_stub_class
  end
end
