# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import textprocessor_pb2 as textprocessor__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in textprocessor_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TextProcessorAStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CountWords = channel.unary_unary(
                '/textprocessor.TextProcessorA/CountWords',
                request_serializer=textprocessor__pb2.TextRequest.SerializeToString,
                response_deserializer=textprocessor__pb2.TextResponse.FromString,
                _registered_method=True)


class TextProcessorAServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CountWords(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TextProcessorAServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CountWords': grpc.unary_unary_rpc_method_handler(
                    servicer.CountWords,
                    request_deserializer=textprocessor__pb2.TextRequest.FromString,
                    response_serializer=textprocessor__pb2.TextResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'textprocessor.TextProcessorA', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('textprocessor.TextProcessorA', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TextProcessorA(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CountWords(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/textprocessor.TextProcessorA/CountWords',
            textprocessor__pb2.TextRequest.SerializeToString,
            textprocessor__pb2.TextResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class TextProcessorBStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CountCharacters = channel.unary_unary(
                '/textprocessor.TextProcessorB/CountCharacters',
                request_serializer=textprocessor__pb2.TextRequest.SerializeToString,
                response_deserializer=textprocessor__pb2.TextResponse.FromString,
                _registered_method=True)


class TextProcessorBServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CountCharacters(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TextProcessorBServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CountCharacters': grpc.unary_unary_rpc_method_handler(
                    servicer.CountCharacters,
                    request_deserializer=textprocessor__pb2.TextRequest.FromString,
                    response_serializer=textprocessor__pb2.TextResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'textprocessor.TextProcessorB', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('textprocessor.TextProcessorB', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TextProcessorB(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CountCharacters(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/textprocessor.TextProcessorB/CountCharacters',
            textprocessor__pb2.TextRequest.SerializeToString,
            textprocessor__pb2.TextResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
