# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: textprocessor.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'textprocessor.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13textprocessor.proto\x12\rtextprocessor\"\x1b\n\x0bTextRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\"\x1e\n\x0cTextResponse\x12\x0e\n\x06result\x18\x01 \x01(\x05\x32W\n\x0eTextProcessorA\x12\x45\n\nCountWords\x12\x1a.textprocessor.TextRequest\x1a\x1b.textprocessor.TextResponse2\\\n\x0eTextProcessorB\x12J\n\x0f\x43ountCharacters\x12\x1a.textprocessor.TextRequest\x1a\x1b.textprocessor.TextResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'textprocessor_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TEXTREQUEST']._serialized_start=38
  _globals['_TEXTREQUEST']._serialized_end=65
  _globals['_TEXTRESPONSE']._serialized_start=67
  _globals['_TEXTRESPONSE']._serialized_end=97
  _globals['_TEXTPROCESSORA']._serialized_start=99
  _globals['_TEXTPROCESSORA']._serialized_end=186
  _globals['_TEXTPROCESSORB']._serialized_start=188
  _globals['_TEXTPROCESSORB']._serialized_end=280
# @@protoc_insertion_point(module_scope)
